apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/Squishyxo/Kubernetes-demo.git
  username: Squishy
  password: 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
