apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Squishyxo/Kubernetes-demo.git
    targetRevision: HEAD
    path: myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
